name: Continous integration
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.puml'
      - '.github/workflows/release.yaml'
jobs:
  ci_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.35.0'
      - uses: extractions/setup-just@v1
      - run: |
          just test
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true
      - run: |
          just k3d
          just up
      - run: |
          just test-e2e

