name: Release
on:
  workflow_dispatch
jobs:
  build_docker_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: master
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - uses: bahmutov/npm-install@v1.7.7
      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.33.0'
      - run: |
          cd master
          npx semantic-release
        env:
          # HELM_EXPERIMENTAL_OCI: 1
          # REGISTRY_USERNAME: ${{ github.repository_owner }}
          # REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir /tmp/cmak
          cp ./master/cmak-operator-*.tgz /tmp/cmak
      - run: |
          cd gh-pages
          helm repo index /tmp/cmak --merge ./index.yaml
          mv -f /tmp/cmak/* .
      - uses: actions-js/push@master
        with:
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

